// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCllAzHbMw0MfemBRGhld3XttLmQsc7OwA',
    appId: '1:949336845819:web:446059c5c07160b3be6f5e',
    messagingSenderId: '949336845819',
    projectId: 'ezhealth-app-77dde',
    authDomain: 'ezhealth-app-77dde.firebaseapp.com',
    storageBucket: 'ezhealth-app-77dde.appspot.com',
    measurementId: 'G-26FTGM445Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-XXCK3aiVwU2fdR75nNK6p8fBGf0U6gw',
    appId: '1:949336845819:android:748e98a83b2cc148be6f5e',
    messagingSenderId: '949336845819',
    projectId: 'ezhealth-app-77dde',
    storageBucket: 'ezhealth-app-77dde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG_7US9ONnnUrVNZ1v8Dhhe66wZnRY-Rw',
    appId: '1:949336845819:ios:1ac6319ebeed6bcebe6f5e',
    messagingSenderId: '949336845819',
    projectId: 'ezhealth-app-77dde',
    storageBucket: 'ezhealth-app-77dde.appspot.com',
    iosClientId: '949336845819-1dl3350g68mjn676l17cvnmllk8t92rg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezhealthApp',
  );
}
